### ISSUE TITLE
Reimplementation for Django 4.2+ Compatibility and Security Enhancement

### ISSUE THREAD

**Issue by shimizukawa** [jazzband/django-redshift-backend#167]
## Current state

- To maintain compatibility of django-redshift-backend, the decision was made to vendor the PostgreSQL backend and Django codebase from Django 4.0 codebase.
- While this approach temporarily ensured compatibility with Redshift, it has resulted in an ongoing situation where new features and fixes from the latest Django versions cannot be incorporated

## Why is it in its current state?

- Redshift is based on the PostgreSQL 8.0.4 interface.
- Django 4.1 and later versions have dropped compatibility with PostgreSQL 10 and below.

## How to fix the issues

- Re-implement this backend independently without relying on the Postgres backend.

## Tasks
- [ ] Investigate the database backend interface for Django 4.2+
- [ ] Investigate the Psycopg3 compatibility with Redshift (postgres 8.0.4) interface
- [ ] Design the new Redshift backend
- [ ] Implement coding and unit tests
- [ ] Conduct compatibility tests with existing applications
- [ ] Update documentation

**Comment by anentropic** [comment]
https://github.com/psycopg/psycopg/issues/122

or should it use:
https://github.com/aws/amazon-redshift-python-driver
?

**Comment by shimizukawa** [comment]
It would be worth trying the amazon-redshift-python-driver. Thank you.
